---
- name: Install traefik
  hosts: all
  become: yes
  gather_facts: false

  vars:
    certificate_email: your@email.com
    traefik_expose_api: "true"
    traefik_api_port: 9080
    traefik_ssl: "true"
  roles:
    - traefik
