---
- name: Install docker-ce latest version
  hosts: all
  become: yes
  gather_facts: false

  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:

  vars:
    pip_install_packages:
      - name: docker
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: latest
    docker_install_compose: True
    docker_compose_version: "1.22.0"
    docker_compose_path: /usr/local/bin/docker-compose
    docker_users:
      - "{{ ansible_ssh_user }}"
  roles:
    - geerlingguy.docker
