---
- hosts: all
  become: true
  become_method: sudo
  vars:
    portainer_container_name: portainer
    portainer_image_tag: latest
    portainer_memory: 64m
    portainer_port: 9000
    portainer_volume: portainer_data
    portainer_systemd_service_name: portainer #### Full name will be docker.portainer.service
  tasks:
### Add portainer service file
    - name: Copy portainer service template to dst server
      template:
####### Change path to tmpl
        src: templates/portainer.tmpl
        dest: /lib/systemd/system/docker.{{ portainer_systemd_service_name }}.service
        owner: root
        group: root
      register: portainerconf
### Reload systemd conf
    - name: Reload systemd-daemon
      systemd:
        name: docker.{{ portainer_systemd_service_name }}.service
        daemon_reload: yes
        state: restarted
      when: portainerconf.changed
### Start docker service and enable autoboot
    - name: Start portainer service and enable autoboot
      systemd:
        name: docker.{{ portainer_systemd_service_name }}.service
        state: started
        enabled: yes
